version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - loggercheck
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gosec
          - makezero
          - rowserrcheck
        path: _test\.go
      - linters:
          - revive
        text: 'var-naming: don''t use an underscore in package name'
      - linters:
          - revive
        text: exported (type|method|function|var|const) (.+) should have comment or be unexported
      - linters:
          - revive
        text: exported (type|method|function|var|const) (.+) should have comment (.+?) or be unexported
    paths:
      - ^zz_generated.*
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(bl-,rootPrj)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - ^zz_generated.*
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  modules-download-mode: readonly
